# Site Settings
title: "Bukombe DevOps Engineer"
description: "DevOps Engineer | Cybersecurity Specialist | Cloud & Automation Enthusiast | Cybersecurity | DevOps | AI & Machine Learning | ISC2 Candidate | IIA Member | IIBA Member | Skilled in Cloud Security, Risk & Compliance"

# Build Settings
markdown: kramdown
highlighter: rouge
# Use the default GitHub Pages-compatible theme or your custom layout
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# URL Settings for user/organization site
baseurl: ""
url: "https://bukombe.github.io"
permalink: pretty

# Author and Social
author:
  name: "Bukombe"
  email: "your.email@example.com"
  github: "bukombe"
  linkedin: "bukombe"

social:
  github: bukombe
  linkedin: bukombe
  twitter: bukombe

# SEO Settings
seo:
  type: Person
  links:
    - "https://github.com/bukombe"
    - "https://linkedin.com/in/bukombe"

# Navigation (for templates that use it)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/#about"
  - title: "Skills"
    url: "/#skills"
  - title: "Projects"
    url: "/#projects"
  - title: "Contact"
    url: "/#contact"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
